FROM node:18

RUN npm i -g nodemon
RUN mkdir -p /home/app

WORKDIR /home/app

EXPOSE 3000

CMD ["nodemon", "index.js"]
#CMD ["node","--watch","index.js"] si no tengo script en package.json

#CMD ["npm", "start"] si en mi package.json tengo un script como: "start": "node --watch index.js"
